### ISSUE TITLE
ack-eliciting packets

### ISSUE THREAD

**Issue by MaxF12** [GrumpyOldTroll/draft-jholland-quic-multicast#3]
Should there be an inclusion that packets including any of the Frames sent over the multicast stream are not ack-eliciting? I assume the intention is to not send ACK frames on the multicast streams but rather use MC_SESSION_ACK. Should there then also be a not ack-eliciting MC_DATA frame that carries the multicast data? Otherwise if STREAM frames are used they would also be ACK eliciting.

**Comment by GrumpyOldTroll** [comment]
What I was thinking is that ack-eliciting frames will elicit an MC_SESSION_ACK on the unicast channel instead of a normal ACK, since there is no reverse path for packets sent over multicast.  Good catch, this should be explicitly spelled out.  Same for MC_PATH_RESPONSE when a PATH_CHALLENGE is received.

**Comment by GrumpyOldTroll** [comment]
Closed via https://github.com/GrumpyOldTroll/draft-jholland-quic-multicast/pull/8
